### ISSUE TITLE
Wrong Item Name

### ISSUE THREAD

**Issue by bariod** [b3none/meloncartel#3] opened 2018-07-22 13:47 UTC
**Describe the bug**
wrong name of item gets displayed in hud. (the knife in this case)

**To Reproduce**
Join the server. yeet

**Expected behavior**
Show knife name with skinname

**Screenshots**
![counter-strike global offensive screenshot 2018 07 22 - 15 15 57 30](https://user-images.githubusercontent.com/35639254/43046235-5a625c44-8dc6-11e8-9c5b-6a4e626ec8ca.png)

**Additional context**
don't know if this occures with other knives aswell

**Comment by B3none** [comment] 2018-07-22 19:47
Hey there, this is actually a strange one which is caused by the new panorama HUD. I noticed that in spectate the knife renaming with the colour set works. I'll implement a panorama check into the knife renaming part of the code and update you on how it goes on.

**Comment by B3none** [comment] 2018-07-22 20:53
Update:
This is now fixed, I added a check whether a client is using panorama and format the nametag accordingly.

![tag-if-panorama](https://user-images.githubusercontent.com/24966460/43050015-9b87530e-8df9-11e8-9cba-592515437a61.jpg)

**Closed as completed by B3none** 2018-07-22 20:53 UTC
